Trackle/trackle/reqs/urls.py
from django.urls import include, path

from .views import pisay, students, teachers

urlpatterns = [
    path('', pisay.home, name='home'),

    path('students/', include(([
        path('', students.RequirementListView.as_view(), name='requirement_list'),
        path('subjects/', students.StudentSubjectsView.as_view(), name='student_subjects'),
        path('finished/', students.TakenRequirementListView.as_view(), name='finished_requirement_list'),
        path('requirement/<int:pk>/', students.take_requirement, name='take_requirement'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.RequirementListView.as_view(), name='req_change_list'),
        path('subjects/add/', teachers.SubjectCreateView.as_view(), name='sub_add'),
        path('requirement/add/', teachers.RequirementCreateView.as_view(), name='req_add'),
        path('requirement/<int:pk>/', teachers.RequirementUpdateView.as_view(), name='requirement_change'),
        path('requirement/<int:pk>/delete/', teachers.RequirementDeleteView.as_view(), name='requirement_delete'),
        path('requirement/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('requirement/<int:requirement_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('requirement/<int:requirement_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'classroom'), namespace='teachers')),
]

Trackle/trackle/trackle/urls.py
from django.contrib import admin
from django.urls import path, include
from reqs.views import pisay, students, teachers

urlpatterns = [
    path('', include("reqs.urls")),
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('signup/', pisay.SignUpView.as_view(), name='signup'),
    path('signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

Trackle/trackle/reqs/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Subject(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subjects')
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Requirement(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='requirements')
    name = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='requirements')
    duedate = models.DateField()

    def __str__(self):
        return self.name


class Question(models.Model):
    requirement = models.ForeignKey(Requirement, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    requirements = models.ManyToManyField(Requirement, through='TakenRequirement')
    subjects = models.ManyToManyField(Subject, related_name='subjected_students')

    def get_unanswered_questions(self, requirement):
        answered_questions = self.requirement_answers \
            .filter(answer__question__requirement=requirement) \
            .values_list('answer__question__pk', flat=True)
        questions = requirement.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class TakenRequirement(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_requirements')
    requirement = models.ForeignKey(Requirement, on_delete=models.CASCADE, related_name='taken_requirements')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='requirement_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

Trackle/trackle/reqs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from reqs.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User, Requirement)

class DateForm(forms.Form):
    date = forms.DateField(input_formats=['%m/%d/%Y'])

class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    subjects = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.subjects.add(*self.cleaned_data.get('subjects'))
        return user


class StudentSubjectsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('subjects', )
        widgets = {
            'subjects': forms.CheckboxSelectMultiple
        }


class RequirementForm(forms.ModelForm):
    class Meta:
        model = Requirement
        fields = ('name', 'subject', 'duedate')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(RequirementForm, self).__init__(*args, **kwargs)
        self.fields['subject'].queryset = Subject.objects.filter(teacher=self.user)

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeRequirementForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

Trackle/trackle/reqs/views/pisay.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:req_change_list')
        else:
            return redirect('students:requirement_list')
    return render(request, 'reqs/home.html')

Trackle/trackle/reqs/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import student_required
from ..forms import StudentSubjectsForm, StudentSignUpForm, TakeRequirementForm
from ..models import Requirement, Student, TakenRequirement, User
from datetime import datetime

class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:requirement_list')


@method_decorator([login_required, student_required], name='dispatch')
class StudentSubjectsView(UpdateView):
    model = Student
    form_class = StudentSubjectsForm
    template_name = 'reqs/students/subjects_form.html'
    success_url = reverse_lazy('students:requirement_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Your subjects have been updated.')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class RequirementListView(ListView):
    model = Requirement
    ordering = ('name', )
    context_object_name = 'requirements'
    template_name = 'reqs/students/requirement_list.html'

    def get_queryset(self):
        student = self.request.user.student
        student_subjects = student.subjects.values_list('pk', flat=True)
        queryset = Requirement.objects.filter(subject__in=student_subjects) \
                .exclude(duedate__lt=datetime.now().date()) \
                .order_by('duedate', 'name', 'subject')
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenRequirementListView(ListView):
    model = TakenRequirement
    context_object_name = 'taken_requirements'
    template_name = 'reqs/students/finished_requirement_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_requirements \
            .select_related('requirement', 'requirement__subject') \
            .order_by('requirement__name')
        return queryset


@login_required
@student_required
def take_requirement(request, pk):
    requirement = get_object_or_404(Requirement, pk=pk)
    student = request.user.student

    if student.requirements.filter(pk=pk).exists():
        return render(request, 'students/taken_requirement.html')

    total_questions = requirement.questions.count()
    unanswered_questions = student.get_unanswered_questions(requirement)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeRequirementForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(requirement).exists():
                    return redirect('students:take_requirement', pk)
                else:
                    correct_answers = student.requirement_answers.filter(answer__question__requirement=requirement, answer__is_correct=True).count()
                    score = round((correct_answers / total_questions) * 100.0, 2)
                    TakenRequirement.objects.create(student=student, requirement=requirement, score=score)
                    if score < 50.0:
                        messages.warning(request, 'Better luck next time! Your score for the requirement %s was %s.' % (requirement.name, score))
                    else:
                        messages.success(request, 'Congratulations! You completed the requirement %s with success! You scored %s points.' % (requirement.name, score))
                    return redirect('students:requirement_list')
    else:
        form = TakeRequirementForm(question=question)

    return render(request, 'reqs/students/take_requirement_form.html', {
        'requirement': requirement,
        'question': question,
        'form': form,
        'progress': progress
    })

Trackle/trackle/reqs/templates/reqs/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:requirement_change' requirement.pk %}">{{ requirement.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'teachers:requirement_change' requirement.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:requirement_change' requirement.pk %}">{{ requirement.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>10</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'teachers:requirement_change' requirement.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
    <a href="{% url 'teachers:question_delete' requirement.pk question.pk %}" class="btn btn-danger float-right">Delete</a>
  </form>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:requirement_change' requirement.pk %}">{{ requirement.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' requirement.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:question_change' requirement.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Cancel</a>
  </form>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/req_add_form.html
{% extends 'base.html' %}

{% block head %}
<!-- Fengyuan Chen’s Datepicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a New Requirement</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a New Requirement</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Add</button>
        <a href="{% url 'teachers:req_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
      </form>
    </div>
  </div>

  <script>
    $(function () {
      $("#id_duedate").datepicker({
        format:'mm/dd/yyyy',
      });
    });
    $('#id_duedate').attr('autocomplete','off');
  </script>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/req_change_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Requirements</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Requirements</h2>
  <a href="{% url 'teachers:req_add' %}" class="btn btn-primary mb-3" role="button">Add a requirement</a>
  <a href="{% url 'teachers:sub_add' %}" class="btn btn-primary mb-3" role="button">Create a subject</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Requirement</th>
          <th>Subject</th>
          <th>Due Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for requirement in requirements %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:requirement_change' requirement.pk %}">{{ requirement.name }}</a></td>
            <td class="align-middle">{{ requirement.subject.get_html_badge }}</td>
            <td class="align-middle">{{ requirement.duedate }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You have no assigned requirements.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/requirement_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ requirement.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ requirement.name }}
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'teachers:req_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
        <a href="{% url 'teachers:requirement_delete' requirement.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'teachers:question_change' requirement.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'teachers:question_add' requirement.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'teachers:question_add' requirement.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/requirement_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:requirement_change' requirement.pk %}">{{ requirement.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the requirement <strong>"{{ requirement.name }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:requirement_change' requirement.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Cancel</a>
  </form>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/requirement_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:requirement_change' requirement.pk %}">{{ requirement.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Results</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ requirement.name }} Results</h2>

  <div class="card">
    <div class="card-header">
      <strong>Taken Requirements</strong>
      <span class="badge badge-pill badge-primary float-right">Average Score: {{ requirement_score.average_score|default_if_none:0.0 }}</span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Student</th>
          <th>Date</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_requirement in taken_requirements %}
          <tr>
            <td>{{ taken_requirement.student.user.username }}</td>
            <td>{{ taken_requirement.date|naturaltime }}</td>
            <td>{{ taken_requirement.score }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      Total respondents: <strong>{{ total_taken_requirements }}</strong>
    </div>
  </div>
{% endblock %}

Trackle/trackle/reqs/templates/reqs/teachers/sub_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:req_change_list' %}">My Requirements</a></li>
      <li class="breadcrumb-item active" aria-current="page">Create a New Subject</li>
    </ol>
  </nav>
  <h2 class="mb-3">Create a New Subject</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Create</button>
        <a href="{% url 'teachers:req_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}